study(title="JAPON İCADI", shorttitle="KIZILDERİLİ BULUTU", overlay=true)

conversionPeriods = input(9, minval=1, title="Conversion Line Periods"),
basePeriods = input(26, minval=1, title="Base Line Periods")
laggingSpan2Periods = input(52, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")

donchian(len) => avg(lowest(len), highest(len))

conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)

plot(conversionLine, color=#0496ff, title="Conversion Line")
plot(baseLine, color=#991515, title="Base Line")
plot(close, offset = -displacement, color=#459915, title="Lagging Span")

p1 = plot(leadLine1, offset = displacement, color=green,
 title="Lead 1")
p2 = plot(leadLine2, offset = displacement, color=red,
 title="Lead 2")
fill(p1, p2, color = leadLine1 > leadLine2 ? green : red)
M1= wma(close, 3)
M2= wma(M1, 5)
M3= wma(M2, 8)
M4= wma(M3, 13)
M5= wma(M4, 21)
MAVW= wma(M5, 34)
plot(MAVW, color=blue, linewidth=2, title="MAVW")

plot(valuewhen(low>low[1] , low[1] , 1), linewidth=2, color=purple, title="TSL")
