//@version=4
study(title="NKRAL1", overlay = true)

// Inputs
a = input(1,     title = "HASSASİYET")
c = input(10,    title = "NKRAL AYARLARI")
h = input(false, title = "FARKLI BAKIŞ")

xATR  = atr(c)
nLoss = a * xATR

src = h ? security(heikinashi(syminfo.tickerid), timeframe.period, close, lookahead = false) : close

xATRTrailingStop = 0.0
xATRTrailingStop := iff(src > nz(xATRTrailingStop[1], 0) and src[1] > nz(xATRTrailingStop[1], 0), max(nz(xATRTrailingStop[1]), src - nLoss),
   iff(src < nz(xATRTrailingStop[1], 0) and src[1] < nz(xATRTrailingStop[1], 0), min(nz(xATRTrailingStop[1]), src + nLoss),
   iff(src > nz(xATRTrailingStop[1], 0), src - nLoss, src + nLoss)))
 
pos = 0   
pos :=	iff(src[1] < nz(xATRTrailingStop[1], 0) and src > nz(xATRTrailingStop[1], 0), 1,
   iff(src[1] > nz(xATRTrailingStop[1], 0) and src < nz(xATRTrailingStop[1], 0), -1, nz(pos[1], 0)))
   
xcolor = pos == -1 ? color.red: pos == 1 ? color.green : color.blue

ema   = ema(src,1)
above = crossover(ema, xATRTrailingStop)
below = crossover(xATRTrailingStop, ema)

buy  = src > xATRTrailingStop and above
sell = src < xATRTrailingStop and below

barbuy  = src > xATRTrailingStop
barsell = src < xATRTrailingStop

plotshape(buy,  title = "Buy",  text = 'AL',  style = shape.labelup,   location = location.belowbar, color= color.green, textcolor = color.white, transp = 0, size = size.small)
plotshape(sell, title = "Sell", text = 'SAT', style = shape.labeldown, location = location.abovebar, color= color.red,   textcolor = color.white, transp = 0, size = size.small)

barcolor(barbuy  ? color.aqua : na)
barcolor(barsell ? color.red   : na)

alertcondition(buy,  "UT Long",  "UT Long")
alertcondition(sell, "UT Short", "UT Short")

length = input(20, minval=1)
arc = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50)
basis = sma(arc, length)
dev = mult * stdev(arc, length)
upper = basis + dev
lower = basis - dev
plot(basis, color=color.black)
p1 = plot(upper, color=color.red)
p2 = plot(lower, color=color.red)
fill(p1, p2)

brc = input(close, title="Source")
length1 = input(5, "EMA")
plot(ema(brc, length1), color=color.black, linewidth=2, title="MOV1")

length2 = input(9, "EMA")
plot(ema(brc, length2), color=color.purple, linewidth=2, title="MOV2")

length3 = input(21, "EMA")
plot(ema(brc, length3), color=color.red, linewidth=2, title="MOV3")

length4 = input(50, "EMA")
plot(ema(brc, length4), color=color.green, linewidth=2, title="MOV4")

length5 = input(100, "EMA")
plot(ema(brc, length5), color=color.orange, linewidth=2, title="MOV5")

length6 = input(200, "EMA")
plot(ema(brc, length6), color=color.blue, linewidth=2, title="MOV6")

length7 = input(377, "EMA")
plot(ema(brc, length7), color=color.purple, linewidth=2, title="MOV7")

length8 = input(610, "EMA")
plot(ema(brc, length8), color=color.green, linewidth=2, title="MOV8")


ema12 = ema(close,12)
plot(ema12, title = "TRİGER", color = color.lime, linewidth = 3)







conversionPeriods = input(9, minval=1, title="Conversion Line Periods"),
basePeriods = input(26, minval=1, title="Base Line Periods")
laggingSpan2Periods = input(52, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")

donchian(len) => avg(lowest(len), highest(len))

conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)

plot(conversionLine, color=#0496ff, title="Conversion Line")
plot(baseLine, color=#991515, title="Base Line")
plot(close, offset = -displacement, color=#459915, title="Lagging Span")

k1 = plot(leadLine1, offset = displacement, color=color.green,
 title="Lead 1")
k2 = plot(leadLine2, offset = displacement, color=color.red,
 title="Lead 2")
fill(k1, k2, color = leadLine1 > leadLine2 ? color.green :color.red)


start = input(0.02)
increment = input(0.02)
maximum = input(0.2)
out = sar(start, increment, maximum)
plot(out, style=plot.style_cross, color=color.blue)

