//@version=2
study(title="Rıza")
len1 = input(title="MA 1", defval = 30)
len2 = input(title="MA 1", defval = 70)

sh = rsi(close, len1)
ln = sma(sh, len2)

p1 = plot(sh, color = black)
p2 = plot(ln, color = red)
mycol = sh > ln ? aqua : red
fill(p1, p2, color=mycol)

buy = (sh[1] < ln [1] and sh > ln)
sell = (sh[1] > ln [1] and sh < ln)
alertcondition(buy, title='Buy', message='RSI Cross. Buy Signal')
alertcondition(sell, title='Sell', message='RSI Cross. Sell Signal')



d0 = hline(70, color=blue)
band1 = hline(30, color=blue)
band2 = hline(50,title="orta", color=black)

