// © BorsaHocam

study(title="S T R ", overlay=true)

ema5 = ema(close,5)
ema21 = ema(close,21)
ema200 = ema(close,200)

plot(ema5, title = "ema5", color = lime, linewidth = 3)
plot(ema21, title = "ema21", color = blue, linewidth = 3)
plot(ema200, title = "ema200", color = red, linewidth = 3)



plot(cross(ema5, ema21) and ema5[1] < ema21[1] ? ema5: na, title="al", style=cross, linewidth=4, color=blue)
plot(cross(ema5, ema21) and ema5[1] > ema21[1] ? ema5 : na, title="sat", style=cross, linewidth=4, color=black)

plotshape(cross(ema5, ema21) and ema5[1] < ema21[1] ? true : na, style=shape.triangleup, text="AL",color=green,size=size.small, location=location.belowbar,transp=0)
plotshape(cross(ema5, ema21) and ema5[1] > ema21[1] ? true : na, style=shape.triangledown, text="SAT",color=black,size=size.small, location=location.abovebar,transp=0)

barcolor(cross(ema5, ema21) and ema5[1] < ema21[1] ? blue: cross(ema5, ema21) and ema5[1] > ema21[1] ? black: close < open ? red: green)

length = input(20, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50, title="StdDev")
basis = sma(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input(0, "Offset", type = integer, minval = -500, maxval = 500)
plot(basis, "Basis", color=#872323, offset = offset)
p1 = plot(upper, "Upper", color=purple, offset = offset)
p2 = plot(lower, "Lower", color=purple, offset = offset)
fill(p1, p2, title = "Background", color=aqua, transp=95)
