//@version=4
strategy("  S T R 2", overlay=true)

start = input(0.02)
increment = input(0.20)
maximum = input(0.2)

psar = sar(start, increment, maximum)

if (psar >= high)
    strategy.entry("AL", strategy.long, stop=psar, comment="AL")
else
    strategy.cancel("AL")

if (psar <= low)
    strategy.entry("SAT", strategy.short, stop=psar, comment="SAT")
else
    strategy.cancel("SAT")

//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)
