study(title="S T R B", overlay=true)

ema5 = ema(close,5)
ema13 = ema(close,13)
ema200 = ema(close,200)

plot(ema5, title = "ema5", color = lime, linewidth = 3)
plot(ema13, title = "ema13", color = blue, linewidth = 3)
plot(ema200, title = "ema200", color = red, linewidth = 3)



plot(cross(ema5, ema13) and ema5[1] < ema13[1] ? ema5: na, title="al", style=cross, linewidth=4, color=blue)
plot(cross(ema5, ema13) and ema5[1] > ema13[1] ? ema5 : na, title="sat", style=cross, linewidth=4, color=black)

plotshape(cross(ema5, ema13) and ema5[1] < ema13[1] ? true : na, style=shape.triangleup, text="AL",color=green,size=size.small, location=location.belowbar,transp=0)
plotshape(cross(ema5, ema13) and ema5[1] > ema13[1] ? true : na, style=shape.triangledown, text="SAT",color=black,size=size.small, location=location.abovebar,transp=0)

barcolor(cross(ema5, ema13) and ema5[1] < ema13[1] ? blue: cross(ema5, ema13) and ema5[1] > ema13[1] ? black: close < open ? red: green)
